### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by whitebeard10** [whitebeard10/sharing-app#1]
improve layout of MainAvtivity.java. you can clone this repo and run it on android studio to duplicate the home page(MainAvtivity.java)

**Comment by narasimha-1511** [comment]
can i work on this issue??
assing it to me
..

**Comment by whitebeard10** [comment]
Hey, thanks for your interest, please feel free to contribute!

**Comment by narasimha-1511** [comment]
hey thankyou started workingon it

**Comment by narasimha-1511** [comment]
should i assemble all those files???

**Comment by whitebeard10** [comment]
here's how you can arrange your files 
![image](https://github.com/whitebeard10/sharing-app/assets/103208764/36059b14-597b-49c9-8fcc-f119baece9de)
![image](https://github.com/whitebeard10/sharing-app/assets/103208764/836651ec-8085-49b3-8b4e-68ccd4a48ac6)

**Comment by RobinKumar5986** [comment]
I would like to work on this issue
So, can I contribute

**Comment by Pratik-Kamble** [comment]
assign issue to me

**Comment by whitebeard10** [comment]
@narasimha-1511 are you still working in this? Else other can take this up

**Comment by narasimha-1511** [comment]
@whitebeard10 bro i had health problem and on oct 12 there i'm having college exam , i will contribute to it on oct 12 after my exam sorry for making it too late. you can unassing the issue if you think its too late

**Comment by whitebeard10** [comment]
@narasimha-1511  hope you are doing ok now, you can take your time, but to qualify for hacktober make sure you complete it before 20th

**Comment by shivank-dvlpr** [comment]
Hey, I also want to contribute in this project.

**Comment by shivank-dvlpr** [comment]
There are some assets are missing and those are using inside the layouts. Should I replace them with something else ?

**Comment by whitebeard10** [comment]
Yas, you can use your own layout but try to sync it around the  theme of the login page

**Comment by shivank-dvlpr** [comment]
hey, why hacktober accepted tag is not validating ?

![Screenshot 2023-10-17 121419](https://github.com/whitebeard10/sharing-app/assets/51983097/8fb57cd6-eeb1-441f-85ec-84fc2e8d2260)

**Comment by whitebeard10** [comment]
it takes time to update, i had labled tghe PR as hacktberfest accepted before merging, you would have gotten mail about the merge.

**Comment by whitebeard10** [comment]
![image](https://github.com/whitebeard10/sharing-app/assets/103208764/c8d0ae5b-8c40-48b9-9773-877d89b860c4)

**Comment by shivank-dvlpr** [comment]
Hey thanks for really quick response and the Update is it accepted.

![Screenshot 2023-10-17 121834](https://github.com/whitebeard10/sharing-app/assets/51983097/81e93622-46e4-455e-b224-68e52698e353)
