### ISSUE TITLE
[feature] add the notification feature.

### ISSUE THREAD

**Issue by whitebeard10** [whitebeard10/sharing-app#6]
it would be nice if it get notification that shows if your request has been accepted or not by your friends.

**Comment by narasimha-1511** [comment]
is this app online or it is static only???

**Comment by whitebeard10** [comment]
currently its on initial stages and lack many features so its not online yet, but eventually it will be launched

**Comment by narasimha-1511** [comment]
how do you get notification without even making it online to pushit changes
